apiVersion: v1
kind: Service
metadata:
  name: be-api-gin
  namespace: ecommerce
  labels:
    app: be-api-gin
    app.kubernetes.io/name: be-api-gin
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: be-api-gin
---
# NodePort service for direct access
apiVersion: v1
kind: Service
metadata:
  name: be-api-gin-nodeport
  namespace: ecommerce
  labels:
    app: be-api-gin
    app.kubernetes.io/name: be-api-gin
    app.kubernetes.io/component: api-gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: be-api-gin
